version: '2.13.0'
services:
  mongodb:
    image: mongo
    container_name: mongo-db
    ports:
      - 2701:2701
    environment:
      MONGO_INITDB_ROOT_USERNAME: abdulfrfr
      MONGO_INITDB_ROOT_PASSWORD: abdulfrfr

  mongo-express:
    image: mongo-express
    container_name: mongo-exp
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: abdulfrfr
      ME_CONFIG_MONGODB_ADMINPASSWORD: abdulfrfr
      ME_CONFIG_MONGODB_SERVER: mongodb
  